### ISSUE TITLE
Deployment fails immediately without waiting, and CodeDeploy console shows nothing

### ISSUE THREAD

**Issue by paambaati** [aws-actions/amazon-ecs-deploy-task-definition#495]
When using this action, the run fails immediately (when it should've waited as I have set the `wait-for-service-stability` flag). Additionally, the console log it prints just takes me to a page where AWS web console complains that the deployment does not exist. In fact, the entire deployments list is empty as this is the first time I'm introducing my team to CodeDeploy.

<img width="1545" alt="Screenshot 2023-06-14 at 7 43 26 PM" src="https://github.com/aws-actions/amazon-ecs-deploy-task-definition/assets/5381764/0f1950e4-619a-4138-8121-95128e7a3362">

Debug output from workflow run –

```
2023-06-14T14:01:30.7412544Z ##[group]Run aws-actions/amazon-ecs-deploy-task-definition@v1
2023-06-14T14:01:30.7412846Z with:
2023-06-14T14:01:30.7413125Z   task-definition: task-definition.json
2023-06-14T14:01:30.7413390Z   cluster: dev-01
2023-06-14T14:01:30.7413614Z   service: web-dev
2023-06-14T14:01:30.7413857Z   codedeploy-appspec: appspec.json
2023-06-14T14:01:30.7414171Z   codedeploy-application: web-dev-codedeploy-app
2023-06-14T14:01:30.7414520Z   codedeploy-deployment-group: web-dev-deployment-group
2023-06-14T14:01:30.7414860Z   wait-for-service-stability: true
2023-06-14T14:01:30.7415101Z env:
2023-06-14T14:01:30.7415309Z   version: v1.0.0
2023-06-14T14:01:30.7415541Z   service: web
2023-06-14T14:01:30.7415752Z   environment: dev
2023-06-14T14:01:30.7415988Z   AWS_DEFAULT_REGION: ap-south-1
2023-06-14T14:01:30.7416231Z   AWS_REGION: ap-south-1
2023-06-14T14:01:30.7416543Z   AWS_ACCESS_KEY_ID: ***
2023-06-14T14:01:30.7416884Z   AWS_SECRET_ACCESS_KEY: ***
=2023-06-14T14:01:30.7419170Z   ACTIONS_STEP_DEBUG: true
2023-06-14T14:01:30.7419404Z ##[endgroup]
2023-06-14T14:01:30.9832231Z ##[debug]Registering the task definition
2023-06-14T14:01:33.1259970Z ##[debug]Updating AppSpec file with new task definition ARN
2023-06-14T14:01:34.1367656Z ##[debug]Starting CodeDeploy deployment
2023-06-14T14:01:35.3235615Z Deployment started. Watch this deployment's progress in the AWS CodeDeploy console: https://console.aws.amazon.com/codesuite/codedeploy/deployments/d-QAPU2SHSN?region=ap-south-1
2023-06-14T14:01:35.3236449Z ##[debug]Waiting for the deployment to complete. Will wait for 33 minutes
2023-06-14T14:01:52.2785594Z ##[error]Resource is not in the state deploymentSuccessful
2023-06-14T14:01:52.2794299Z ##[debug]ResourceNotReady: Resource is not in the state deploymentSuccessful
2023-06-14T14:01:52.2794832Z ##[debug]    at constructor.setError (/home/runner/work/_actions/aws-actions/amazon-ecs-deploy-task-definition/v1/dist/index.js:23477:47)
2023-06-14T14:01:52.2795422Z ##[debug]    at Request.CHECK_ACCEPTORS (/home/runner/work/_actions/aws-actions/amazon-ecs-deploy-task-definition/v1/dist/index.js:23339:12)
2023-06-14T14:01:52.2796015Z ##[debug]    at Request.callListeners (/home/runner/work/_actions/aws-actions/amazon-ecs-deploy-task-definition/v1/dist/index.js:24559:20)
2023-06-14T14:01:52.2796558Z ##[debug]    at Request.emit (/home/runner/work/_actions/aws-actions/amazon-ecs-deploy-task-definition/v1/dist/index.js:24531:10)
2023-06-14T14:01:52.2797070Z ##[debug]    at Request.emit (/home/runner/work/_actions/aws-actions/amazon-ecs-deploy-task-definition/v1/dist/index.js:23165:14)
2023-06-14T14:01:52.2797611Z ##[debug]    at Request.transition (/home/runner/work/_actions/aws-actions/amazon-ecs-deploy-task-definition/v1/dist/index.js:22501:10)
2023-06-14T14:01:52.2798169Z ##[debug]    at AcceptorStateMachine.runTo (/home/runner/work/_actions/aws-actions/amazon-ecs-deploy-task-definition/v1/dist/index.js:29527:12)
2023-06-14T14:01:52.2798716Z ##[debug]    at /home/runner/work/_actions/aws-actions/amazon-ecs-deploy-task-definition/v1/dist/index.js:29539:10
2023-06-14T14:01:52.2799635Z ##[debug]    at Request.<anonymous> (/home/runner/work/_actions/aws-actions/amazon-ecs-deploy-task-definition/v1/dist/index.js:22517:9)
2023-06-14T14:01:52.2800157Z ##[debug]    at Request.<anonymous> (/home/runner/work/_actions/aws-actions/amazon-ecs-deploy-task-definition/v1/dist/index.js:23167:12)
2023-06-14T14:01:52.2826655Z ##[debug]Node Action run completed with exit code 1
2023-06-14T14:01:52.2829812Z ##[debug]Set output task-definition-arn = arn:aws:ecs:ap-south-1:***:task-definition/web-dev:9
2023-06-14T14:01:52.2830284Z ##[debug]Set output codedeploy-deployment-id = d-QAPU2SHSN
2023-06-14T14:01:52.2833196Z ##[debug]Finishing: Deploy ECS task using CodeDeploy
```

**Comment by paambaati** [comment]
I guess the quotas hadn't kicked in yet (OR) CodeDeploy took a while to initialize, but after a few hours, the dashboard shows up and all of the deployment include logs. I was then able to debug issues and fix.
